Name:Bhavika Sachin Avhad Branch:IT Information Technology


In [5]:
import numpy as np




In [6]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((4,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.arange(28,400,5)

array([ 28,  33,  38,  43,  48,  53,  58,  63,  68,  73,  78,  83,  88,
        93,  98, 103, 108, 113, 118, 123, 128, 133, 138, 143, 148, 153,
       158, 163, 168, 173, 178, 183, 188, 193, 198, 203, 208, 213, 218,
       223, 228, 233, 238, 243, 248, 253, 258, 263, 268, 273, 278, 283,
       288, 293, 298, 303, 308, 313, 318, 323, 328, 333, 338, 343, 348,
       353, 358, 363, 368, 373, 378, 383, 388, 393, 398])

In [14]:
np.block(arr)


array([1, 2, 3, 4, 5])

In [18]:
np.add(6,12)

np.int64(18)

In [32]:

arr=np.array([[2,3,4],[5,6,7],[8,9,0]])

In [37]:
arr.ndim

2

In [35]:
arr.shape

(3, 3)

In [38]:
arr.dtype

dtype('int64')